superquadric-model: SuperqVisualization Class Reference
SuperqVisualization Class Reference
This class shows the point cloud used for modeling or the estimated superquadric overlapped on the camera image and in real time.
#include <superqVisualization.h>
Inherits RateThread.
Public Member Functions
SuperqVisualization (int rate, const std::string &_eye, const std::string &_what_to_plot, yarp::sig::Vector &_x, yarp::sig::Vector &_x_filtered, std::deque< int > &_Color, yarp::dev::IGazeControl *_igaze, const yarp::sig::Matrix _K, std::deque< yarp::sig::Vector > &_points, const int &_vis_points, const int &_vis_step)
bool showPoints ()
Show point cloud on the image.
bool showSuperq (yarp::sig::Vector &x_to_show)
Show reconstructed superquadric on the image.
yarp::sig::Vector from3Dto2D (const yarp::sig::Vector &point3D)
Compute 2D pixels from 3D points.
virtual bool threadInit ()
Init function of RateThread.
virtual void run ()
Run function of RateThread.
void interruptPorts ()
Interrupt ports functionalities.
virtual void threadRelease ()
Release function of RateThread.
void setPar (const std::string &par_name, const std::string &value)
Set a given parameter equal to a string.
void setPar (const std::string &par_name, const int &value)
Set a given parameter equal to a desired value.
void setColor (const int &r, const int &g, const int &b)
Set color for visualization.
void setPar (const yarp::os::Property &newOptions, bool first_time)
Set parameters for visualization.
yarp::os::Property getPar ()
Get parameters for visualization.
double getTime ()
Get time required for visualization.
Data Fields
yarp::sig::Vector & superq
Estimated superquadric.
yarp::sig::Vector & superq_filtered
Filtered superquadric.
std::deque< yarp::sig::Vector > & points
Object point cloud.
yarp::sig::ImageOf< yarp::sig::PixelRgb > * imgIn
Input image.
Protected Attributes
yarp::os::BufferedPort< yarp::sig::ImageOf< yarp::sig::PixelRgb > > portImgIn
Input image port.
yarp::os::BufferedPort< yarp::sig::ImageOf< yarp::sig::PixelRgb > > portImgOut
Output image port *.
int r
R value for visualization.
int g
Green value for visualization.
int b
Blue value for visualization.
double t_vis
Time for visualization.
int vis_points
Number of points used for visualization.
int vis_step
Number of visualization step.
std::string what_to_plot
String used for deciding what to plot: "points" or "superq".
yarp::sig::Vector point
yarp::sig::Vector point1
yarp::sig::Vector point2D
std::deque< int > Color
std::string eye
Eye camera selected.
yarp::sig::Matrix R
yarp::sig::Matrix H
yarp::sig::Matrix K
yarp::dev::IGazeControl * igaze
Gaze Control interface.
yarp::os::Mutex mutex
Detailed Description
This class shows the point cloud used for modeling or the estimated superquadric overlapped on the camera image and in real time.
Definition at line 36 of file superqVisualization.h.
Member Function Documentation
from3Dto2D()
Vector SuperqVisualization::from3Dto2D (const yarp::sig::Vector & point3D)
Compute 2D pixels from 3D points.
Parameters
point3D is the 3D point to be converted
Returns
a 2D vector representing the corresponding pixel
Definition at line 168 of file superqVisualization.cpp.
Referenced by showPoints(), and showSuperq().
 {
     Vector point2D(3,0.0);
     Vector point_aux(4,1.0);
     point_aux.setSubvector(0,point3D);
     point2D=K*H*point_aux;
     return point2D.subVector(0,1)/point2D[2];
 }
getPar()
Property SuperqVisualization::getPar ()
Get parameters for visualization.
Returns
a property with all the visualization options
Definition at line 330 of file superqVisualization.cpp.
References eye, vis_points, vis_step, and what_to_plot.
 {
     LockGuard lg(mutex);
     Property advOptions;
     advOptions.put("visualized_points",vis_points);
     if (Color[0]==255 && Color[1]==0 && Color[2]==0)
         advOptions.put("color","red");
     else if  (Color[0]==0 && Color[1]==255 && Color[2]==0)
         advOptions.put("color","green");
     else if  (Color[0]==0 && Color[1]==0 &&Color[2]==255)
         advOptions.put("color","blue");
     advOptions.put("camera",eye);
     advOptions.put("visualized_points_step",vis_step);
     advOptions.put("what_to_plot",what_to_plot);
     return advOptions;
 }
getTime()
double SuperqVisualization::getTime ()
Get time required for visualization.
Returns
the visualization time
Definition at line 349 of file superqVisualization.cpp.
References t_vis.
 {
     LockGuard lg(mutex);
     return t_vis;
 }
setColor()
void SuperqVisualization::setColor (const int & r, const int & g, const int & b)
Set color for visualization.
Parameters
r is the red component
g is the green component
b is the blue component
setPar() [1/3]
void SuperqVisualization::setPar (const std::string & par_name, const std::string & value)
Set a given parameter equal to a string.
Parameters
par_name is the name of the parameter to be changed
value is the new value
setPar() [2/3]
void SuperqVisualization::setPar (const std::string & par_name, const int & value)
Set a given parameter equal to a desired value.
Parameters
par_name is the name of the parameter to be changed
value is the new value
setPar() [3/3]
void SuperqVisualization::setPar (const yarp::os::Property & newOptions, bool first_time)
Set parameters for visualization.
Parameters
newOptions is a Property with the new options to set
first_time takes into account if the options have already been set or not
showPoints()
bool SuperqVisualization::showPoints ()
Show point cloud on the image.
Returns
true
Definition at line 117 of file superqVisualization.cpp.
References eye, from3Dto2D(), igaze, imgIn, points, portImgOut, and vis_step.
Referenced by run().
 {
     PixelRgb color(Color[0],Color[1],Color[2]);
     Stamp *stamp=NULL;
     Vector pos, orient;
     ImageOf<PixelRgb> &imgOut=portImgOut.prepare();
     imgOut=*imgIn;
     if (eye=="left")
     {
         if (igaze->getLeftEyePose(pos,orient,stamp))
         {
             H=axis2dcm(orient);
             H.setSubcol(pos,0,3);
             H=SE3inv(H);
         }
     }
     else
     {
         if (igaze->getRightEyePose(pos,orient,stamp))
         {
             H=axis2dcm(orient);
             H.setSubcol(pos,0,3);
             H=SE3inv(H);
         }
     }
     Vector point(3,0.0);
      for (size_t i=0; i<points.size(); i+=vis_step)
      {
          point=points[i].subVector(0,2);
          point2D=from3Dto2D(point);
          cv::Point target_point((int)point2D[0],(int)point2D[1]);
          if ((target_point.x<0) || (target_point.y<0) || (target_point.x>=320) || (target_point.y>=240))
          {
              yWarning("[SuperqVisualization]:  Not acceptable pixels!");
          }
          else
             imgOut.pixel(target_point.x, target_point.y)=color;
      }
     portImgOut.write();
     return true;
 }
showSuperq()
bool SuperqVisualization::showSuperq (yarp::sig::Vector & x_to_show)
Show reconstructed superquadric on the image.
Parameters
x_to_show is the superquadric to be shown
Returns
true/false on success/failure
Definition at line 39 of file superqVisualization.cpp.
References eye, from3Dto2D(), igaze, imgIn, portImgOut, and vis_points.
Referenced by run().
 {
     LockGuard lg(mutex);
     PixelRgb color(Color[0],Color[1],Color[2]);
     Vector pos, orient;
     double co,so,ce,se;
     Stamp *stamp=NULL;
     ImageOf<PixelRgb> &imgOut=portImgOut.prepare();
     imgOut=*imgIn;
     R=euler2dcm(x_toshow.subVector(8,10));
     R=R.transposed();
     if ((norm(x_toshow)>0.0))
     {
         if (eye=="left")
         {
             if (igaze->getLeftEyePose(pos,orient,stamp))
             {
                 H=axis2dcm(orient);
                 H.setSubcol(pos,0,3);
                 H=SE3inv(H);
             }
         }
         else
         {
             if (igaze->getRightEyePose(pos,orient,stamp))
             {
                 H=axis2dcm(orient);
                 H.setSubcol(pos,0,3);
                 H=SE3inv(H);
             }
         }
         double step=2*M_PI/vis_points;
         for (double eta=-M_PI; eta<M_PI; eta+=step)
         {
              for (double omega=-M_PI; omega<M_PI;omega+=step)
              {
                  co=cos(omega); so=sin(omega);
                  ce=cos(eta); se=sin(eta);
                  point[0]=x_toshow[0] * sign(ce)*(pow(abs(ce),x_toshow[3])) * sign(co)*(pow(abs(co),x_toshow[4])) * R(0,0) +
                             x_toshow[1] * sign(ce)*(pow(abs(ce),x_toshow[3]))* sign(so)*(pow(abs(so),x_toshow[4])) * R(0,1)+
                                 x_toshow[2] * sign(se)*(pow(abs(se),x_toshow[3])) * R(0,2) + x_toshow[5];
                  point[1]=x_toshow[0] * sign(ce)*(pow(abs(ce),x_toshow[3])) * sign(co)*(pow(abs(co),x_toshow[4])) * R(1,0) +
                             x_toshow[1] * sign(ce)*(pow(abs(ce),x_toshow[3])) * sign(so)*(pow(abs(so),x_toshow[4])) * R(1,1)+
                                 x_toshow[2] * sign(se)*(pow(abs(se),x_toshow[3])) * R(1,2) + x_toshow[6];
                  point[2]=x_toshow[0] * sign(ce)*(pow(abs(ce),x_toshow[3])) * sign(co)*(pow(abs(co),x_toshow[4])) * R(2,0) +
                             x_toshow[1] * sign(ce)*(pow(abs(ce),x_toshow[3])) * sign(so)*(pow(abs(so),x_toshow[4])) * R(2,1)+
                                 x_toshow[2] * sign(se)*(pow(abs(se),x_toshow[3])) * R(2,2) + x_toshow[7];
                  point2D=from3Dto2D(point);
                  cv::Point target_point((int)point2D[0],(int)point2D[1]);
                  if ((target_point.x<0) || (target_point.y<0) || (target_point.x>=320) || (target_point.y>=240))
                  {
                      yWarning("[SuperqVisualization]: Not acceptable pixels!");
                  }
                  else
                     imgOut.pixel(target_point.x, target_point.y)=color;
              }
          }
     }
     portImgOut.write();
     return true;
 }
The documentation for this class was generated from the following files:
C:/Users/upattacini/Desktop/superquadric-model/include/superqVisualization.h
C:/Users/upattacini/Desktop/superquadric-model/src/superqVisualization.cpp